import socket
import pickle
from dotenv import load_dotenv
import os
import time
from tcp_packet import TCPPacket
from udp_tcp_socket import TCPOverUDPSocket




load_dotenv()
port = int(os.getenv("PORT",8080))
address= os.getenv("ADDRESS","localhost")
timeout = int(os.getenv("TIMEOUT",1))

ADDR=(address,port)



# create a UDP socket
# udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
# udp_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

udp_socket = TCPOverUDPSocket()
udp_socket.settimeout(timeout)
udp_socket.connect(ADDR)

flag = True
while flag:
    try:
        flag = False

        file = open("./alice.txt", "r")

        message = "hhahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaahahahahhahahahahaaaahahahhahahahahaa"
        # read whole file
        message = file.read()
        # message =" checkckck"

        udp_socket.send(message)

    except socket.timeout:
        pass

# close the socket
print("Closing client")
udp_socket.close()
print("Client closed")
